In [3]:
#13/07/2025
#Tamim Mahmud from Daffodil International University
import numpy as np


In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a.ndim

1

In [8]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
b.dtype

dtype('int32')

In [12]:
type(b)

numpy.ndarray

In [13]:
a.size

3

In [14]:
b.size

6

In [15]:
s=np.zeros((3,3),dtype='int')

In [16]:
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
x=np.zeros([5,5],dtype='int')
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
y=np.ones([6,6],dtype='int')
y

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [19]:
s=np.full((5,5),6)
s

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [20]:
s=np.full((10,9),100)
s

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [22]:
m=np.identity(10,dtype='int')
m

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
d=np.identity(3,dtype='int')
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
ar=np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [25]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
s=np.arange(12).reshape(4,3)
s

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
s.ndim

2

In [29]:
d=np.arange(18).reshape(6,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [30]:
d.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [31]:
f=np.arange(27).reshape(3,3,3)
f

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
f.ndim

3

In [33]:
ss=np.arange(64).reshape(4,4,4)
ss

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [34]:
l=np.linspace(1,5,10)
l

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
l.ndim

1

In [36]:
ass=np.random.randint(1,10,size=(2,3,3))
ass

array([[[1, 9, 4],
        [2, 9, 4],
        [7, 1, 3]],

       [[2, 4, 4],
        [9, 9, 4],
        [3, 8, 7]]])

In [37]:
f=np.random.randint(1,100,(10,6,6))
f

array([[[78, 26,  5, 76,  4, 29],
        [39, 56, 22, 27, 81, 14],
        [ 6, 55, 28, 34, 96, 26],
        [47, 14, 48, 83, 64, 54],
        [11, 93, 45, 56, 83, 92],
        [95, 72,  1,  2, 39, 98]],

       [[98, 17, 64, 30,  5, 19],
        [37, 30, 56, 99, 16, 82],
        [11, 31, 22, 78, 16, 19],
        [26, 22, 46, 43, 85, 45],
        [76, 36, 36, 38, 17,  7],
        [52, 26, 61,  3,  8, 75]],

       [[24, 86, 28, 61, 67, 92],
        [69, 96, 79, 19, 17, 63],
        [54, 64,  4, 43, 31, 14],
        [70,  9, 64,  9, 96, 59],
        [75, 82, 64, 38, 34, 36],
        [ 1, 64, 66, 55, 87, 62]],

       [[87,  2, 22, 68, 50, 15],
        [ 4, 28,  5, 82, 86, 95],
        [91, 57, 33, 73, 68,  9],
        [46, 37, 95, 54, 92, 45],
        [70, 62, 13, 99, 89, 95],
        [78,  2, 57, 38, 46, 74]],

       [[12, 19, 33,  9, 94, 49],
        [84, 38, 97, 80, 33, 28],
        [ 5, 93, 22, 85,  1, 60],
        [48, 22, 67, 94, 87, 47],
        [75, 60, 56, 25,  7, 91],
      

In [38]:
dd=np.random.randint(1,10,(5,3,3))
dd

array([[[3, 9, 2],
        [1, 3, 2],
        [5, 6, 1]],

       [[8, 4, 2],
        [7, 2, 6],
        [9, 5, 4]],

       [[2, 1, 9],
        [8, 7, 2],
        [7, 8, 4]],

       [[8, 3, 9],
        [5, 2, 9],
        [3, 7, 5]],

       [[6, 5, 8],
        [7, 5, 3],
        [7, 3, 2]]])

In [39]:
dd.ndim

3

In [40]:
dd.size

45

In [47]:
a=np.random.randint(1,10,(2,3))
a


array([[5, 5, 6],
       [1, 1, 6]])

In [44]:
a=np.ravel(a)
a

array([1, 9, 8, 6, 2, 7])

In [45]:
a.ndim

1

In [48]:
a.ravel()

array([5, 5, 6, 1, 1, 6])

In [49]:
a[0]=0
a

array([[0, 0, 0],
       [1, 1, 6]])

In [50]:
a.ravel()

array([0, 0, 0, 1, 1, 6])

In [51]:
a.flatten()

array([0, 0, 0, 1, 1, 6])

In [52]:
a

array([[0, 0, 0],
       [1, 1, 6]])

In [55]:
a=a.flatten()
a


array([0, 0, 0, 1, 1, 6])

In [56]:
a.flatten()

array([0, 0, 0, 1, 1, 6])

In [58]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
y=2*x
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [60]:
np.hstack((x,y))


array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [63]:
np.column_stack((x,y))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [64]:
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [65]:
np.row_stack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [67]:
np.concatenate((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [68]:
np.dstack((x,y))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [69]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.sum()

45

In [71]:
a.mean()

4.5

In [73]:
np.median(a)

4.5

In [74]:
np.std(a)

2.8722813232690143

In [75]:
np.var(a)

8.25

In [76]:
a.min()

0

In [77]:
a.max()

9

In [78]:
a.argmin()

0

In [79]:
a.argmax()

9

In [80]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
a.sum(axis=0)

array([ 9, 12, 15])

In [83]:
a.sum(axis=1)

array([ 3, 12, 21])

In [84]:
a+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [85]:
b=np.random.randint(1,10,(3,3))
b

array([[1, 5, 6],
       [3, 7, 9],
       [3, 8, 5]])

In [86]:
np.dot(a,b)

array([[  9,  23,  19],
       [ 30,  83,  79],
       [ 51, 143, 139]])

In [90]:
c=a@b
c

array([[  9,  23,  19],
       [ 30,  83,  79],
       [ 51, 143, 139]])

In [89]:
np.linalg.inv(b)

array([[-0.90243902,  0.56097561,  0.07317073],
       [ 0.29268293, -0.31707317,  0.2195122 ],
       [ 0.07317073,  0.17073171, -0.19512195]])

In [91]:
np.linalg.inv(c)

array([[-3.72243557e+14,  7.44487115e+14, -3.72243557e+14],
       [ 2.18693090e+14, -4.37386180e+14,  2.18693090e+14],
       [-8.84078449e+13,  1.76815690e+14, -8.84078449e+13]])

In [92]:
values,vectors=np.linalg.eig(c)


In [93]:
values

array([ 2.28465703e+02,  2.53429724e+00, -8.41814312e-15])

In [95]:
vectors

array([[ 0.12621373,  0.84843629,  0.84468302],
       [ 0.49340402,  0.17433693, -0.49625128],
       [ 0.86059431, -0.49976243,  0.20061222]])

In [96]:
np.transpose(c)

array([[  9,  30,  51],
       [ 23,  83, 143],
       [ 19,  79, 139]])

In [97]:
np.linalg.det(c)

-6.447391640182013e-13

In [98]:
np.linalg.det(b)

41.00000000000001

In [101]:
a=np.arange(45,100,10)
a

array([45, 55, 65, 75, 85, 95])

In [102]:
l=[(a>50)&(a<70)]
l

[array([False,  True,  True, False, False, False])]

In [103]:
#Alhamdulillah--
#13/06/2025